obj-$(CONFIG_MXGBE) += rnpgbe.o
rnpgbe-objs :=   \
		rnpgbe_main.o \
		rnpgbe_common.o \
		rnpgbe_debugfs.o \
		rnpgbe_ethtool.o \
		rnpgbe_lib.o \
		rnpgbe_mbx.o \
		rnpgbe_chip.o \
		rnpgbe_mbx_fw.o\
		rnpgbe_sriov.o \
		rnpgbe_param.o \
		rnp_compat.o \
		rnpgbe_sysfs.o \
		rnpgbe_ptp.o \
		rnpgbe_sfc.o 

