# SPDX-License-Identifier: GPL-2.0
#
# Makefile for LoongArch-specific library files..
#

lib-y	+= delay.o memcpy.o memset.o memmove.o \
	   copy_user.o clear_user.o strncpy_user.o strnlen_user.o unaligned.o

obj-$(CONFIG_CPU_GENERIC_DUMP_TLB) += dump_tlb.o
