#ifndef __DT_BINDINGS_PINCTRL_LS2K300_H
#define __DT_BINDINGS_PINCTRL_LS2K300_H

#define PINCTL_FUNCTIONGPIO        0
#define PINCTL_FUNCTION1           1
#define PINCTL_FUNCTION2           2
#define PINCTL_FUNCTIONMAIN        3

#endif
